#!/bin/bash
##############################################
##                                          ##
##  Menu                                    ##
##  Launches menu_kali-1.py                 ##
##  Best autostarted through ~/.profile     ##
##                                          ##
##############################################


export FRAMEBUFFER=/dev/fb1
export MENUDIR="/home/pi/Kali-Pi/Menus/"
export SCREENSIZE=3.5     ## Options= 3.5, 2.8
startpage="menu-1.py"
/usr/bin/clear
/bin/bash $MENUDIR/launch-bg.sh
/usr/bin/env python $MENUDIR$startpage
